Repository Pick-IT-SSU/backend, pull requests merged in 2022-02, with the labels that each got.

#9 [MOD] 이메일 중복체크 API
  src/main/java/com/example/demo/auth/CustomOAuth2Service.java
  src/main/java/com/example/demo/auth/CustomUserDetails.java
  src/main/java/com/example/demo/auth/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/controller/UserController.java
  src/main/java/com/example/demo/domain/User.java
Labels: 소민, Modify, 회원관리

#11 [FEAT] 깃허브 닉네임 중복체크 API, JWT 추가
  build.gradle
  src/main/java/com/example/demo/auth/CustomOAuth2Service.java
  src/main/java/com/example/demo/auth/JwtAuthenticationFilter.java
  src/main/java/com/example/demo/auth/JwtTokenProvider.java
  src/main/java/com/example/demo/auth/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/auth/WebMvcConfig.java
  src/main/java/com/example/demo/auth/WebSecurityConfig.java
  src/main/java/com/example/demo/controller/UserController.java
  src/main/java/com/example/demo/dataObject/dto/AuthResponse.java
  src/main/java/com/example/demo/domain/User.java
Labels: 소민, FEAT, Add, 회원관리

#12 [FIX] Codedeploy Scripts 오류 해결
  appspec.yml
  scripts/deploy.sh
  src/main/java/com/example/demo/auth/WebMvcConfig.java
  src/main/java/com/example/demo/controller/UserController.java
  src/test/java/com/example/demo/DemoApplicationTests.java
Labels: 은주, CHORE, FIX, SETTING

#13 [FIX] 깃허브 소셜로그인 무한 요청 해결
  src/main/java/com/example/demo/auth/CustomOAuth2Service.java
  src/main/java/com/example/demo/auth/WebSecurityConfig.java
  src/main/java/com/example/demo/controller/UserController.java
Labels: 소민, 회원관리, FIX

#15 [CHORE] deploy 파일 코드 수정
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
Labels: 은주, CHORE, SETTING

#17 [CHORE] Properties 값 추가
  src/main/java/com/example/demo/controller/UserController.java
  src/main/resources/application.properties
Labels: 은주, CHORE, SETTING

#18 [DEL] application.properties 삭제
  src/main/resources/application.properties
Labels: 은주, DEL, SETTING

#21 [FEAT] 스터디글 등록, 상세글 조회 API
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/controller/UserController.java
  src/main/java/com/example/demo/domain/StudyPost.java
  src/main/java/com/example/demo/domain/User.java
  src/main/java/com/example/demo/dto/AuthResponse.java
  src/main/java/com/example/demo/dto/ResponseMessage.java
  src/main/java/com/example/demo/dto/SigninDTO.java
  src/main/java/com/example/demo/dto/SignupDTO.java
  src/main/java/com/example/demo/dto/StudyPostDTO.java
  src/main/java/com/example/demo/repository/StudyPostRepository.java
  src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/demo/service/StudyPostService.java
  src/main/java/com/example/demo/util/AES256.java
Labels: 소민, FEAT, ADD, 스터디

#23 [FEAT] 강의 등록 API
  .gitignore
  build.gradle
  src/main/java/com/example/demo/controller/LectureController.java
  src/main/java/com/example/demo/controller/ReviewController.java
  src/main/java/com/example/demo/domain/Lecture.java
  src/main/java/com/example/demo/domain/Review.java
  src/main/java/com/example/demo/domain/StudyPost.java
  src/main/java/com/example/demo/domain/User.java
  src/main/java/com/example/demo/dto/LectureDto.java
  src/main/java/com/example/demo/repository/LectureRepository.java
  src/main/java/com/example/demo/repository/ReviewRepository.java
  src/main/java/com/example/demo/security/CustomUserDetails.java
  src/main/java/com/example/demo/service/LectureService.java
  src/main/java/com/example/demo/service/ReviewService.java
Labels: 은주, FEAT, ADD, MOD, FIX, 스터디

#24 [FEAT]스터디글 수정 API
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/controller/UserController.java
  src/main/java/com/example/demo/domain/StudyPost.java
  src/main/java/com/example/demo/dto/StudyPostDTO.java
  src/main/java/com/example/demo/service/StudyPostService.java
Labels: FEAT, MOD, 스터디

#25 [FEAT]스터디글 좋아요 API, 전체글 조회 API
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/domain/Interested.java
  src/main/java/com/example/demo/domain/Lecture.java
  src/main/java/com/example/demo/domain/Report.java
  src/main/java/com/example/demo/domain/Review.java
  src/main/java/com/example/demo/domain/StudyPost.java
  src/main/java/com/example/demo/domain/User.java
  src/main/java/com/example/demo/repository/InterestedRepository.java
  src/main/java/com/example/demo/repository/ReportRepository.java
  src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/demo/service/InterestedService.java
  src/main/java/com/example/demo/service/ReportService.java
  src/main/java/com/example/demo/service/StudyPostService.java
Labels: 소민, FEAT, 스터디

#26 [FEAT] 단어가 포함된 해시태그 조회 API
  build.gradle
  src/main/java/com/example/demo/QueryDslConfig.java
  src/main/java/com/example/demo/controller/HashtagController.java
  src/main/java/com/example/demo/controller/LectureController.java
  src/main/java/com/example/demo/domain/Hashtag.java
  src/main/java/com/example/demo/dto/HashtagDto.java
  src/main/java/com/example/demo/dto/LectureDto.java
  src/main/java/com/example/demo/repository/CustomHashtagRepository.java
  src/main/java/com/example/demo/repository/CustomHashtagRepositoryImpl.java
  src/main/java/com/example/demo/repository/HashTagRepository.java
  src/main/java/com/example/demo/repository/LectureRepository.java
  src/main/java/com/example/demo/service/HashtagService.java
  src/main/java/com/example/demo/service/LectureService.java
  src/main/java/com/example/demo/service/ReviewService.java
Labels: 은주, FEAT, CHORE, 강의 리뷰

#28 [FEAT]스터디글 모든 param 조회 API
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/repository/StudyPostRepositoryCustom.java
  src/main/java/com/example/demo/repository/StudyPostRepositoryCustomImpl.java
  src/main/java/com/example/demo/service/StudyPostService.java
Labels: 소민, FEAT, 스터디

#32 [MOD] entity fk명 변경
  src/main/java/com/example/demo/controller/LectureController.java
  src/main/java/com/example/demo/domain/Lecture.java
  src/main/java/com/example/demo/domain/Review.java
  src/main/java/com/example/demo/domain/ReviewHashtag.java
  src/main/java/com/example/demo/service/LectureService.java
Labels: 은주, MOD

#36 [FEAT]스터디 댓글 등록, 수정 API
  src/main/java/com/example/demo/controller/StudyCommentController.java
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/domain/Report.java
  src/main/java/com/example/demo/domain/StudyComment.java
  src/main/java/com/example/demo/domain/StudyPost.java
  src/main/java/com/example/demo/domain/User.java
  src/main/java/com/example/demo/dto/AllStudyPostsResponse.java
  src/main/java/com/example/demo/dto/DetailStudyPostResponse.java
  src/main/java/com/example/demo/dto/StudyCommentDto.java
  src/main/java/com/example/demo/dto/StudyCommentResponse.java
  src/main/java/com/example/demo/dto/UserOnlyDto.java
  src/main/java/com/example/demo/repository/InterestedRepository.java
  src/main/java/com/example/demo/repository/LikeRepository.java
  src/main/java/com/example/demo/repository/StudyCommentRepository.java
  src/main/java/com/example/demo/service/LikeService.java
  src/main/java/com/example/demo/service/StudyCommentService.java
  src/main/java/com/example/demo/service/StudyPostService.java
Labels: 소민, FEAT, 스터디

#39 [FEAT]회원탈퇴 API, status code 수정
  src/main/java/com/example/demo/controller/StudyCommentController.java
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/controller/UserController.java
  src/main/java/com/example/demo/repository/UserRepository.java
  src/main/java/com/example/demo/security/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
Labels: 소민, FEAT, MOD, 회원관리

#45 [ADD] 특정 강의글 조회 API 코드 추가
  src/main/java/com/example/demo/controller/LectureController.java
  src/main/java/com/example/demo/domain/Like.java
  src/main/java/com/example/demo/dto/LectureOnlyDto.java
  src/main/java/com/example/demo/dto/LectureResponse.java
  src/main/java/com/example/demo/dto/ReviewOnlyDto.java
  src/main/java/com/example/demo/repository/HashtagRepository.java
  src/main/java/com/example/demo/repository/LectureRepository.java
  src/main/java/com/example/demo/repository/ReviewHashtagRepository.java
  src/main/java/com/example/demo/repository/ReviewRepository.java
  src/main/java/com/example/demo/service/HashtagService.java
  src/main/java/com/example/demo/service/LectureService.java
  src/main/java/com/example/demo/service/ReviewService.java
Labels: ADD, FIX

#46 [FEAT] 강의 좋아요 등록/취소 API
  src/main/java/com/example/demo/controller/LectureController.java
  src/main/java/com/example/demo/controller/ReviewController.java
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/domain/Lecture.java
  src/main/java/com/example/demo/domain/Like.java
  src/main/java/com/example/demo/dto/LectureResponse.java
  src/main/java/com/example/demo/dto/ReviewOnlyDto.java
  src/main/java/com/example/demo/repository/CustomLikeRepository.java
  src/main/java/com/example/demo/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/repository/LikeRepository.java
  src/main/java/com/example/demo/service/LectureService.java
  src/main/java/com/example/demo/service/LikeService.java
Labels: 은주, FEAT, ADD, MOD, 강의 리뷰

#47 [DEL]likes, reports divison 삭제
  src/main/java/com/example/demo/controller/StudyCommentController.java
  src/main/java/com/example/demo/controller/StudyController.java
  src/main/java/com/example/demo/domain/Like.java
  src/main/java/com/example/demo/domain/Report.java
Labels: 소민, MOD, DEL

#48 [FEAT] 강의 리뷰 수정 API
  src/main/java/com/example/demo/controller/ReviewController.java
  src/main/java/com/example/demo/dto/ReviewDto.java
  src/main/java/com/example/demo/repository/CustomReviewRepository.java
  src/main/java/com/example/demo/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/example/demo/repository/ReviewRepository.java
  src/main/java/com/example/demo/service/LectureService.java
  src/main/java/com/example/demo/service/ReviewService.java
Labels: FEAT, MERGE

#52 [FIX] import 오류 수정
  src/main/java/com/example/demo/hashtag/repository/CustomHashtagRepositoryImpl.java
  src/main/java/com/example/demo/hashtag/repository/HashtagRepository.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/example/demo/study/repository/CustomStudyPostRepositoryImpl.java
Labels: 은주, FIX

#53 [MOD] 전체 스터디글, 상세 스터디글 조회 response 수정
  src/main/java/com/example/demo/like/LikeService.java
  src/main/java/com/example/demo/like/repository/LikeRepository.java
  src/main/java/com/example/demo/study/controller/StudyController.java
  src/main/java/com/example/demo/study/dto/AllStudyPostsResponse.java
  src/main/java/com/example/demo/study/dto/DetailStudyPostResponse.java
  src/main/java/com/example/demo/study/dto/StudyCommentResponse.java
  src/main/java/com/example/demo/study/repository/CustomStudyCommentRepository.java
  src/main/java/com/example/demo/study/repository/CustomStudyCommentRepositoryImpl.java
  src/main/java/com/example/demo/study/repository/StudyCommentRepository.java
  src/main/java/com/example/demo/study/service/StudyCommentService.java
  src/main/java/com/example/demo/study/service/StudyPostService.java
  src/main/java/com/example/demo/user/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/user/dto/DetailUserDto.java
  src/main/java/com/example/demo/user/dto/SimpleUserDto.java
Labels: 소민, MOD, 스터디
