Repository Pick-IT-SSU/backend, pull requests merged in 2022-03, with the labels that each got.

#54 [FEAT] 로드맵 등록, 등록 위한 강의 조회 API
  src/main/java/com/example/demo/review/ReviewService.java
  src/main/java/com/example/demo/review/repository/ReviewRepository.java
  src/main/java/com/example/demo/roadmap/RoadMap.java
  src/main/java/com/example/demo/roadmap/RoadMapService.java
  src/main/java/com/example/demo/roadmap/dto/RoadMapDto.java
  src/main/java/com/example/demo/roadmap/dto/RoadmapLecturesResponse.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/repository/RoadMapRepository.java
  src/main/java/com/example/demo/roadmap/roadMapController.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
Labels: 소민, FEAT, 로드맵

#55 [FEAT] 리뷰 등록 / 강의 전체 조회 및 신고 API
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/dto/AllLecturesResponse.java
  src/main/java/com/example/demo/lecture/dto/DetailLectureResponse.java
  src/main/java/com/example/demo/report/Report.java
  src/main/java/com/example/demo/report/ReportRepository.java
  src/main/java/com/example/demo/report/ReportService.java
  src/main/java/com/example/demo/review/Review.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/review/ReviewService.java
  src/main/java/com/example/demo/review/dto/DetailReviewResponse.java
  src/main/java/com/example/demo/review/dto/ReviewDto.java
  src/main/java/com/example/demo/review/dto/ReviewPostDto.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepository.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/example/demo/reviewHashtag/ReviewHashtagService.java
  src/main/java/com/example/demo/user/User.java
Labels: 은주, FEAT, ADD, MOD, 강의 리뷰

#56 [FIX]소셜로그인 후 redirect
  src/main/java/com/example/demo/report/Report.java
  src/main/java/com/example/demo/report/ReportRepository.java
  src/main/java/com/example/demo/report/ReportService.java
  src/main/java/com/example/demo/security/CustomSuccessHandler.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/main/java/com/example/demo/study/controller/StudyCommentController.java
  src/main/java/com/example/demo/study/controller/StudyController.java
  src/main/java/com/example/demo/user/UserController.java
  src/main/java/com/example/demo/user/UserDetailsServiceImpl.java
Labels: 소민, 회원관리, FIX

#58 [FEAT] 상세 로드맵 조회 API
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/like/LikeService.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepository.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/like/repository/LikeRepository.java
  src/main/java/com/example/demo/roadmap/RoadMap.java
  src/main/java/com/example/demo/roadmap/RoadMapService.java
  src/main/java/com/example/demo/roadmap/dto/DetailRoadmapLectureResponse.java
  src/main/java/com/example/demo/roadmap/dto/DetailRoadmapResponse.java
  src/main/java/com/example/demo/roadmap/dto/RoadmapUploadLectureDto.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/roadMapController.java
  src/main/java/com/example/demo/study/controller/StudyController.java
  src/main/java/com/example/demo/study/service/StudyPostService.java
  src/main/java/com/example/demo/user/User.java
Labels: 소민, FEAT, 로드맵

#59 [FEAT] 강의리뷰 필터링 조회 API
  build.gradle
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/repository/LectureRepository.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/example/demo/review/repository/ReviewRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepositoryImpl.java
  src/test/java/com/example/demo/DemoApplicationTests.java
Labels: 은주, FEAT, MOD, FIX, 강의 리뷰

#60 [FEAT] 로드맵 좋아요, 수정, 삭제 API
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/like/LikeService.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/RoadMap.java
  src/main/java/com/example/demo/roadmap/RoadMapService.java
  src/main/java/com/example/demo/roadmap/dto/DetailRoadmapResponse.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/repository/RoadMapRepository.java
  src/main/java/com/example/demo/roadmap/roadMapController.java
Labels: 소민, FEAT, 로드맵

#61 [FEAT] flask로 추천용 데이터 전송
  build.gradle
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/data/ExcelData.java
  src/main/java/com/example/demo/lecture/dto/RecLecturesResponse.java
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/like/LikeService.java
  src/main/java/com/example/demo/like/repository/LikeRepository.java
  src/main/java/com/example/demo/review/Review.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
Labels: 은주, FEAT, ADD, CHORE, MOD, FIX, 강의 리뷰

#63 [FEAT] 추천 알고리즘용 테스트 데이터 post API
  build.gradle
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/dto/ExcelData.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
Labels: 은주, FEAT, MOD, 강의 리뷰

#64 [REFACTOR] 로드맵 데이터베이스 변경
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/like/LikeService.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepository.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/like/repository/LikeRepository.java
  src/main/java/com/example/demo/roadmap/RoadMap.java
  src/main/java/com/example/demo/roadmap/RoadMapService.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadMapRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/repository/RoadMapRepository.java
  src/main/java/com/example/demo/roadmap/roadMapController.java
  src/main/java/com/example/demo/user/User.java
Labels: 소민, REFACTOR, 로드맵

#65 [ADD] RoadmapGroup 엔티티
  src/main/java/com/example/demo/roadmap/RoadMapGroup.java
Labels: 소민, ADD, 로드맵

#66 [REFACTOR] 로드맵 등록, 상세조회, 수정, 삭제, 좋아요 API
  src/main/java/com/example/demo/like/LikeService.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepository.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/RoadMapGroup.java
  src/main/java/com/example/demo/roadmap/RoadmapController.java
  src/main/java/com/example/demo/roadmap/dto/DetailRoadmapResponse.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/repository/RoadmapGroupRepository.java
  src/main/java/com/example/demo/roadmap/repository/RoadmapRepository.java
  src/main/java/com/example/demo/roadmap/service/RoadmapGroupService.java
  src/main/java/com/example/demo/roadmap/service/RoadmapService.java
Labels: 소민, FEAT, REFACTOR, 로드맵

#68 [FEAT] 전체 로드맵 조회 API
  src/main/java/com/example/demo/roadmap/RoadmapController.java
  src/main/java/com/example/demo/roadmap/dto/AllRoadmapsResponse.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapGroupRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapGroupRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/repository/RoadmapGroupRepository.java
  src/main/java/com/example/demo/roadmap/service/RoadmapGroupService.java
Labels: 소민, FEAT, 로드맵

#69 [FEAT] 마이페이지 강의 리뷰 / 스터디 API
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepository.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/LikedLecturesResponse.java
  src/main/java/com/example/demo/mypage/dto/LikedStudiesResponse.java
  src/main/java/com/example/demo/mypage/dto/MyReviewsResponse.java
  src/main/java/com/example/demo/mypage/dto/MyStudiesResponse.java
  src/main/java/com/example/demo/study/repository/CustomStudyPostRepository.java
  src/main/java/com/example/demo/study/repository/CustomStudyPostRepositoryImpl.java
  src/main/java/com/example/demo/study/service/StudyPostService.java
  src/main/java/com/example/demo/user/UserController.java
Labels: 은주, FEAT, 마이페이지

#70 [FEAT] 좋아요 / 작성한 로드맵 API
  src/main/java/com/example/demo/like/repository/CustomLikeRepository.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/LikedRoadmapsResponse.java
  src/main/java/com/example/demo/mypage/dto/MyRoadmapsResponse.java
  src/main/java/com/example/demo/roadmap/dto/AllRoadmapsResponse.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapGroupRepository.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapGroupRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/repository/CustomRoadmapRepositoryImpl.java
  src/main/java/com/example/demo/roadmap/service/RoadmapGroupService.java
Labels: 은주, FEAT, 마이페이지

#73 [FEAT] 해시태그 전체 목록 조회
  build.gradle
  src/main/java/com/example/demo/AwsS3Config.java
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/SwaggerConfig.java
  src/main/java/com/example/demo/hashtag/Hashtag.java
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/hashtag/service/HashtagService.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/dto/AllLecturesResponse.java
  src/main/java/com/example/demo/lecture/dto/LectureDto.java
  src/main/java/com/example/demo/mypage/CommonUtils.java
  src/main/java/com/example/demo/mypage/ImageService.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/MyInfoEditDto.java
  src/main/java/com/example/demo/mypage/dto/MyInfoResponse.java
  src/main/java/com/example/demo/user/UserController.java
  src/main/java/com/example/demo/user/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/user/repository/UserRepository.java
Labels: FEAT, ADD

#74 [MOD] 해시태그 전체 조회 권한 수정
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/main/java/com/example/demo/user/User.java
Labels: 은주, MOD, 강의 리뷰

#75 [FEAT] 이메일 소속인증 API
  build.gradle
  src/main/java/com/example/demo/user/Company.java
  src/main/java/com/example/demo/user/UserCompanyRepository.java
  src/main/java/com/example/demo/user/UserController.java
  src/main/java/com/example/demo/user/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/user/dto/CompanyCertificateDto.java
  src/main/java/com/example/demo/user/dto/CompanyNameKey.java
  src/main/java/com/example/demo/user/dto/SimpleUserDto.java
Labels: 소민, FEAT, 회원관리

#76 [FEAT] 프로필 공개여부 변경 API
  build.gradle
  src/main/java/com/example/demo/hashtag/service/HashtagService.java
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/dto/AllLecturesResponse.java
  src/main/java/com/example/demo/lecture/dto/LectureDto.java
  src/main/java/com/example/demo/lecture/repository/LectureRepository.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/InfoEditMapper.java
  src/main/java/com/example/demo/mypage/dto/InfoResponse.java
  src/main/java/com/example/demo/mypage/dto/MyInfoEditDto.java
  src/main/java/com/example/demo/mypage/dto/MyPageResponse.java
  src/main/java/com/example/demo/reviewHashtag/ReviewHashtagService.java
  src/main/java/com/example/demo/roadmap/service/RoadmapService.java
  src/main/java/com/example/demo/study/domain/StudyPost.java
  src/main/java/com/example/demo/user/User.java
Labels: 은주, FEAT, ADD, CHORE, MOD, MERGE, 강의 리뷰

#77 [FIX] Swagger 오류 수정
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/dto/MyInfoEditDto.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/user/User.java
Labels: 은주, FIX

#78 [MOD] 강의 리뷰 등록 API 수정 및 강의글 상세조회 리팩토링
  src/main/java/com/example/demo/hashtag/Hashtag.java
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/dto/AllLecturesResponse.java
  src/main/java/com/example/demo/lecture/dto/DetailLectureResponse.java
  src/main/java/com/example/demo/lecture/dto/LectureDto.java
  src/main/java/com/example/demo/lecture/dto/LectureUrlResponse.java
  src/main/java/com/example/demo/lectureHashtag/LectureHashtag.java
  src/main/java/com/example/demo/lectureHashtag/LectureHashtagRepository.java
  src/main/java/com/example/demo/lectureHashtag/LectureHashtagService.java
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/InfoEditMapper.java
  src/main/java/com/example/demo/mypage/dto/LikedStudiesResponse.java
  src/main/java/com/example/demo/mypage/dto/MyPageResponse.java
  src/main/java/com/example/demo/review/Review.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/reviewHashtag/ReviewHashtagRepository.java
  src/main/java/com/example/demo/reviewHashtag/ReviewHashtagService.java
  src/main/java/com/example/demo/roadmap/RoadmapController.java
  src/main/java/com/example/demo/roadmap/service/RoadmapService.java
  src/main/java/com/example/demo/user/User.java
Labels: 은주, ADD, MOD, REFACTOR, 강의 리뷰

#79 [ADD] 로드맵 전체글 조회 페이징, 스터디 전체글 정렬, 소속인증 요청 팝업창 처리
  src/main/java/com/example/demo/roadmap/RoadmapController.java
  src/main/java/com/example/demo/roadmap/dto/UserRoadmapCompanyDto.java
  src/main/java/com/example/demo/roadmap/repository/RoadmapGroupRepository.java
  src/main/java/com/example/demo/roadmap/repository/RoadmapSpecification.java
  src/main/java/com/example/demo/roadmap/service/RoadmapGroupService.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/main/java/com/example/demo/study/controller/StudyController.java
  src/main/java/com/example/demo/study/repository/CustomStudyPostRepository.java
  src/main/java/com/example/demo/study/repository/CustomStudyPostRepositoryImpl.java
  src/main/java/com/example/demo/study/repository/StudyPostRepository.java
  src/main/java/com/example/demo/study/service/StudyPostService.java
  src/main/java/com/example/demo/study/util/StudyPostLikeCalc.java
  src/main/java/com/example/demo/study/util/StudyPostLikeComparator.java
  src/main/java/com/example/demo/user/UserController.java
  src/main/java/com/example/demo/user/UserDetailsServiceImpl.java
Labels: 소민, FEAT, ADD, MOD, 스터디, 로드맵

#80 [ADD/MOD] 강의 등록 관리자 권한 API 추가 및 강의 조회 코드 변경
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/RequestedLecture.java
  src/main/java/com/example/demo/lecture/repository/LectureRepository.java
  src/main/java/com/example/demo/lecture/repository/LectureSpecification.java
  src/main/java/com/example/demo/lecture/repository/RequestedLectureRepository.java
  src/main/java/com/example/demo/user/UserController.java
  src/main/java/com/example/demo/user/dto/SignupDTO.java
Labels: 은주, ADD, MOD, FIX, 강의 리뷰
