Repository Pick-IT-SSU/backend, pull requests merged in 2022-05, with the labels that each got.

#83 [ADD] 사용자 선호도 해시태그 테이블
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/report/Report.java
  src/main/java/com/example/demo/roadmap/RoadMap.java
  src/main/java/com/example/demo/study/domain/StudyComment.java
  src/main/java/com/example/demo/study/domain/StudyPost.java
  src/main/java/com/example/demo/userPreferenceHashtag/UserHashtagPreferenceRepository.java
  src/main/java/com/example/demo/userPreferenceHashtag/UserPreferenceHashtag.java
  src/main/java/com/example/demo/userPreferenceHashtag/UserPreferenceHashtagService.java
Labels: 소민, ADD, 강의 리뷰

#86 [MOD/ADD] 강의 내 리뷰 작성 시 강의 데이터 전송
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/dto/LectureUrlResponse.java
Labels: 은주, ADD, MOD, 강의 리뷰

#87 [MOD] 사용자 해시태그 선호도 DB - 마지막 좋아요 시간 필드 추가
  src/main/java/com/example/demo/userPreferenceHashtag/UserPreferenceHashtag.java
Labels: 소민, MOD, 강의 리뷰

#88 [FIX] 강의글에 해당하는 리뷰 출력 안되는 오류 수정
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/review/ReviewController.java
Labels: 은주, FIX, 강의 리뷰

#89 [FIX] 좋아요한 로드맵, 스터디글 조회
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/example/demo/user/UserController.java
Labels: MOD, FIX, 마이페이지

#90 [FIX] 리뷰 조회/닉네임 표시/평점 업데이트 오류 수정
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/dto/LectureDto.java
  src/main/java/com/example/demo/lecture/repository/LectureRepository.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/review/ReviewService.java
  src/main/java/com/example/demo/review/dto/DetailReviewResponse.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepositoryImpl.java
Labels: 은주, FIX, 강의 리뷰

#91 [ADD] 로드맵 조회 전체 데이터 response 코드 추가
  src/main/java/com/example/demo/roadmap/RoadmapController.java
  src/main/java/com/example/demo/roadmap/repository/RoadmapGroupRepository.java
  src/main/java/com/example/demo/roadmap/service/RoadmapGroupService.java
Labels: 소민, ADD, 로드맵
