Repository Pick-IT-SSU/backend, pull requests merged in 2022-06, with the labels that each got.

#95 [Mod] 추천 알고리즘 전송용 메소드 forEach 추가
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/dto/AllLecturesForRecommendResponse.java
  src/main/java/com/example/demo/lecture/dto/LikedLecturesForRecommendResponse.java
Labels: 은주, MOD, 강의 리뷰

#96 [FEAT] redis-refreshToken 추가 및 토큰 재발급 기능 구현, 로그아웃 기능 구현
  build.gradle
  src/main/java/com/example/demo/RedisConfig.java
  src/main/java/com/example/demo/security/AuthResponse.java
  src/main/java/com/example/demo/security/CustomSuccessHandler.java
  src/main/java/com/example/demo/security/LogoutTokenRepository.java
  src/main/java/com/example/demo/security/RefreshTokenRepository.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/main/java/com/example/demo/security/domain/LogoutToken.java
  src/main/java/com/example/demo/security/domain/RefreshToken.java
  src/main/java/com/example/demo/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/demo/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/demo/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/demo/user/UserController.java
  src/main/java/com/example/demo/user/UserDetailsServiceImpl.java
  src/main/java/com/example/demo/user/dto/ReissueDto.java
Labels: 소민, FEAT, CHORE, 회원관리

#98 [MOD] 추천 알고리즘 전송용 메소드 API 수정
  .github/workflows/deploy.yml
  appspec.yml
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/like/RecommendService.java
  src/main/java/com/example/demo/like/RecommendedLecture.java
  src/main/java/com/example/demo/study/controller/StudyController.java
Labels: 은주, MOD, 강의 리뷰

#99 [FIX/REFACTOR] 마이페이지 정보 수정 / 리뷰 재작성 시 오류 수정 및 코드 정리
  appspec.yml
  scripts/deploy.sh
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/LikedLecturesResponse.java
  src/main/java/com/example/demo/mypage/dto/MyReviewsResponse.java
  src/main/java/com/example/demo/review/Review.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/review/ReviewService.java
  src/main/java/com/example/demo/review/dto/ReviewDto.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepository.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/example/demo/review/repository/ReviewRepository.java
  src/main/java/com/example/demo/user/domain/User.java
Labels: 은주, MOD, FIX, REFACTOR, 강의 리뷰, 마이페이지

#101 [ADD] RequestedLecture 및 추천알고리즘 전송 코드 추가
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/RequestedLecture.java
  src/main/java/com/example/demo/like/RecommendService.java
  src/main/java/com/example/demo/like/RecommendedLecture.java
Labels: 은주, ADD, MOD, 강의 리뷰

#102 [ADD] 크롤링 테스트 코드, 노마드코더 크롤러
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/main/java/com/example/demo/util/Crawler.java
Labels: ADD

#103 [FEAT] 프로젝트 라이언, 유데미, 패스트캠퍼스 크롤러
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/util/Crawler.java
Labels: 은주, FEAT, 강의 리뷰

#106 [MOD/ADD] 프로젝트 라이언, 패스트 캠퍼스, 생활코딩 크롤러
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/util/Crawler.java
Labels: 은주, ADD, MOD, 강의 리뷰

#107 [MOD] 크롤러 비동기 처리
  src/main/java/com/example/demo/AsyncConfig.java
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/hashtag/service/HashtagService.java
  src/main/java/com/example/demo/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/demo/util/Crawler.java
Labels: MOD, DEL, 강의 리뷰

#109 [ADD/FEAT] lectureController 크롤러 연결, 마이페이지-강의 등록 내역 확인 API
  src/main/java/com/example/demo/hashtag/HashtagController.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/RequestedLecture.java
  src/main/java/com/example/demo/lecture/repository/RequestedLectureRepository.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/RequestedLectureResponse.java
  src/main/java/com/example/demo/user/domain/User.java
  src/main/java/com/example/demo/util/Crawler.java
Labels: ADD, MOD

#114 [FIX] 마이페이지-좋아요한 스터디 조회 사용자 정보 수정
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/mypage/dto/LikedStudiesResponse.java
Labels: FIX, 마이페이지

#115 [FIX] 강의 조회 오류 수정
  src/main/java/com/example/demo/lecture/Lecture.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/RecommendLectureController.java
  src/main/java/com/example/demo/lecture/RecommendService.java
  src/main/java/com/example/demo/lecture/dto/DetailLectureResponse.java
  src/main/java/com/example/demo/review/ReviewService.java
Labels: 은주, MOD, FIX, 강의 리뷰

#116 [FIX] 로드맵 조회- 삭제된 리뷰 처리
  src/main/java/com/example/demo/roadmap/service/RoadmapService.java
Labels: FIX, 로드맵

#117 [FIX] 사용자 기본 프로필 url 추가
  src/main/java/com/example/demo/user/domain/User.java
Labels: 회원관리, FIX

#118 [FIX] 강의 조회 시 좋아요 개수/여부 수정 및 좋아요 한 로드맵 조회 오류 수정
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/lecture/LectureController.java
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/lecture/RecommendService.java
  src/main/java/com/example/demo/lecture/dto/AllLecturesResponse.java
  src/main/java/com/example/demo/like/Like.java
  src/main/java/com/example/demo/mypage/MyPageController.java
  src/main/java/com/example/demo/mypage/MyPageService.java
  src/main/java/com/example/demo/security/WebSecurityConfig.java
  src/test/java/com/example/demo/DemoApplicationTests.java
Labels: 은주, FIX, 강의 리뷰, 마이페이지

#119 [FIX] 강의 좋아요 관련 오류 수정
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/like/repository/CustomLikeRepositoryImpl.java
Labels: 은주, FIX, 강의 리뷰

#120 [FIX] 이메일 '' 포함 수정
  src/main/java/com/example/demo/user/UserController.java
Labels: 소민, FIX, 마이페이지

#121 [FIX] 강의리뷰 수정 시 평점 반영 오류 수정
  src/main/java/com/example/demo/lecture/LectureService.java
  src/main/java/com/example/demo/review/ReviewController.java
  src/main/java/com/example/demo/review/ReviewService.java
  src/main/java/com/example/demo/review/repository/CustomReviewRepositoryImpl.java
Labels: 은주, FIX, 강의 리뷰
